### ISSUE TITLE
增加說明

### ISSUE THREAD

**Issue by yijutseng** [DHLab-TSENG/lab#1]
1. getTimeSeriesLab
https://dhlab-tseng.github.io/lab/reference/getTS.html 裏面
indexDate的說明內有說可以自己放日期，但沒有寫要放欄位名稱
indexDate first last的大小寫說明文件跟範例檔不同，是"First"還是“first”?

2. imputeTimeSeriesLab
https://dhlab-tseng.github.io/lab/reference/impTS.html
impMethod沒有nocb

**Comment by mircyam** [comment]
兩個都改好了，
目前都以小寫為主，但不確定是否要改成 case-insensitive？
