### ISSUE TITLE
getAbnormalMark() referenceTable column name match

### ISSUE THREAD

**Issue by yijutseng** [DHLab-TSENG/lab#4]
referenceTable = refLOINC
if the column name of LOINC in refLOINC table does not match the column name of LOINC in lab data, user will get error message
merge.data.table(labData, referenceTable, by = labCols, all.x = TRUE)：
  Elements listed in `by` must be valid column names in x and y

**Comment by mircyam** [comment]
應該要讓他們用引數對齊？還是在說明文件上面標記需要同名？

**Comment by yijutseng** [comment]
我覺得要同名很難，不然你就先寫清楚要同名，並舉個例好了

**Comment by yijutseng** [comment]
https://github.com/DHLab-TSENG/lab/commit/f865fb99ea634fe6d43bce67481d8ec7b8c9fec5
