### ISSUE TITLE
plotTimeSeriesLab with abnormalMarkColName=TURE

### ISSUE THREAD

**Issue by yijutseng** [DHLab-TSENG/lab#5]
`timeSeriesData <- getTimeSeriesLab(labData = loincSample,
                                   idColName = SUBJECT_ID,
                                   labItemColName = LOINC + LABEL,
                                   dateColName = CHARTTIME,
                                   valueColName = VALUENUM,
                                   indexDate = first,
                                   gapDate = 30,
                                   completeWindows = TRUE)
colnames(patientSample)[2]<-"ID"
timeSeriesDataMarked <- getAbnormalMark(labData = timeSeriesData,
                                     idColName = ID,
                                     labItemColName = LOINC,
                                     valueColName = Nearest,
                                     genderColName = GENDER,
                                     genderTable = patientSample,
                                     referenceTable = refLOINC)

timeSeriesPlotMarked <- plotTimeSeriesLab(labData = timeSeriesDataMarked,
                                    idColName = ID,
                                    labItemColName = LOINC + LABEL,
                                    timeMarkColName = Window,
                                    valueColName = Value,
                                    timeStart = 1,
                                    timeEnd  = 5,
                                    abnormalMarkColName = ABMark)

plot(timeSeriesPlotMarked)`

![00001e](https://user-images.githubusercontent.com/8377506/172826686-6dc175e5-d3fd-4f38-bc50-af19425277ed.png)

**Comment by mircyam** [comment]
處理分子群失敗的問題，以及斷點問題。

為了讓畫面稍微好看一點，也微調了圖示跟線/點尺寸，目前結果長這樣，之後可以再微調：
![image](https://user-images.githubusercontent.com/52523083/175523615-6a8dd1b7-7b0d-4379-9c6e-e63c5d4015f4.png)
（例如加入標準值範圍的輔助線）
