### ISSUE TITLE
plotTimeSeriesLab() line disconnected

### ISSUE THREAD

**Issue by yijutseng** [DHLab-TSENG/lab#6]
![time](https://user-images.githubusercontent.com/8377506/172878258-a7fec87b-6d99-42b8-9d9d-5fa354ef726f.png)
`
timeSeriesData <- getTimeSeriesLab(labData = loincSample,
                                   idColName = SUBJECT_ID,
                                   labItemColName = LOINC + LABEL,
                                   dateColName = CHARTTIME,
                                   valueColName = VALUENUM,
                                   indexDate = first,
                                   gapDate = 30,
                                   completeWindows = TRUE)
timeSeriesPlot <- plotTimeSeriesLab(labData = timeSeriesData,
                                    idColName = ID,
                                    labItemColName = LOINC + LABEL,
                                    timeMarkColName = Window,
                                    valueColName = Nearest,
                                    timeStart = 1,
                                    timeEnd  = 5,
                                    abnormalMarkColName = NULL)

plot(timeSeriesPlot)
`

**Comment by mircyam** [comment]
如果要讓它 connect 的話，前一步驟應該要先 impute，或是預設幫它 impute？

**Comment by yijutseng** [comment]
不impute應該也可以連起來？因為是連續數值，如果沒有資料就沒點這樣

**Comment by mircyam** [comment]
更正好了，問題的原因是 ggplot2 如果讀到 window 值是 NA，線就不會連續，把 NA 的 window 直接刪掉可以解決這個問題。
![image](https://user-images.githubusercontent.com/52523083/175519195-bf8a306a-4b2a-4df1-b4f2-74b321ebbb52.png)

如果只有單點的話就還是單點。
